# Generated by Django 4.1.3 on 2022-12-03 21:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('title', models.CharField(max_length=500, null=True)),
                ('description', models.TextField(max_length=700, null=True)),
                ('event_type', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField()),
                ('event_location', models.CharField(max_length=300, null=True)),
                ('image', models.ImageField(blank=True, default='event-imgs/img-8.jpg', null=True, upload_to='')),
                ('event_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.profile')),
            ],
        ),
    ]
