# Generated by Django 4.1.3 on 2022-12-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_rename_event_type_event_category_event_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='ticket_number',
            new_name='total_tickets',
        ),
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
