# Generated by Django 4.1.3 on 2022-12-05 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='event_title',
        ),
    ]
