# Generated by Django 4.1.3 on 2022-12-05 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_rename_title_event_event_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_title',
            new_name='title',
        ),
    ]
