# Generated by Django 4.1.3 on 2022-12-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_rename_event_title_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gps_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='event-imgs/img-8.jpg', null=True, upload_to='event-imgs'),
        ),
    ]
