# Generated by Django 4.1.3 on 2022-12-08 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
    ]
