# Generated by Django 4.1.3 on 2022-12-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_profile_image'),
        ('event', '0014_alter_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='saved', to='user.profile'),
        ),
    ]
