# Generated by Django 4.1.3 on 2022-12-14 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_event_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='saved',
        ),
    ]
