# Generated by Django 4.1.3 on 2022-12-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile-imgs/avatar.svg', null=True, upload_to='profile-imgs'),
        ),
    ]
